#!/usr/bin/env bash
# Fixes Nginx to run as nginx user and listen on port 8080
useradd --system --no-create-home --shell /bin/false nginx || true
sed -Ei 's/^\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
service nginx restart || service nginx start
