#!/usr/bin/env bash
# This script stops Nginx, checks that it's not running, and then restarts it.

sudo service nginx stop
service nginx status | grep -q "is not running" && echo "Nginx is stopped"
sudo service nginx start
