#!/usr/bin/env bash
# This script transfers a file to a remote server using SCP.

# Check if there are less than 4 parameters
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file to the user's home directory (~) on the remote server
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~/"

# Check if the transfer was successful
if [ $? -eq 0 ]; then
  echo "File transfer successful!"
else
  echo "File transfer failed."
fi
