#!/usr/bin/env bash
# Update package index and install nginx
sudo apt update -y
sudo apt install nginx -y

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/location \//a \\t#error_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration
sudo systemctl restart nginx
